# Generated by Django 4.0.6 on 2022-11-16 07:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import mdeditor.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='自增主键')),
                ('title', models.CharField(max_length=100, verbose_name='文章标题')),
                ('intro', models.CharField(max_length=300, verbose_name='文章简介')),
                ('content_text', mdeditor.fields.MDTextField(verbose_name='文章正文')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='发布时间')),
                ('number', models.IntegerField(verbose_name='阅读量')),
                ('like_numbers', models.IntegerField(default=0, verbose_name='点赞量')),
            ],
        ),
        migrations.CreateModel(
            name='Friend_site',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='自增ID')),
                ('name', models.CharField(max_length=64, verbose_name='网站名称')),
                ('site', models.CharField(max_length=128, verbose_name='网址')),
                ('remark', models.CharField(max_length=64, null=True, verbose_name='备注')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='添加时间')),
            ],
        ),
        migrations.CreateModel(
            name='Ip',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ip', models.CharField(max_length=30, verbose_name='IP地址')),
                ('count', models.IntegerField(default=0, verbose_name='访问次数')),
                ('visit_time', models.DateField(auto_now=True, verbose_name='访问时间')),
                ('location', models.CharField(default=' ', max_length=30, verbose_name='IP归属地')),
            ],
        ),
        migrations.CreateModel(
            name='Sort',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='自增主键')),
                ('name', models.CharField(max_length=10, verbose_name='分类')),
            ],
        ),
        migrations.CreateModel(
            name='Like_number',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='点赞时间')),
                ('article_id', models.OneToOneField(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='blog.article', verbose_name='关联USER模型，一对一')),
                ('ip_id', models.OneToOneField(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='blog.ip', verbose_name='关联ip模型，一对一')),
            ],
            options={
                'verbose_name': '用户点赞',
                'verbose_name_plural': '用户点赞',
            },
        ),
        migrations.AddField(
            model_name='article',
            name='sort',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='blog.sort', verbose_name='分类外键'),
        ),
        migrations.AddField(
            model_name='article',
            name='user',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户外键'),
        ),
    ]
